import type { ElementTypeCatalogEntry } from '../types'

/**
 * 9 ana prefabrik ÜST YAPI eleman tipi.
 * Prompt paketi — 03/04/05/06/07 master liste dosyaları.
 */
export const ELEMENT_TYPES: ElementTypeCatalogEntry[] = [
  {
    id: 'col',
    nameTr: 'Kolon',
    nameEn: 'Column',
    defaultCode: 'KL',
    ifcClass: 'IfcColumn',
    defaultIfcPredefinedType: 'COLUMN',
    category: 'superstructure',
    order: 10,
    description: 'Prefabrik kolon (IfcColumn).',
    allowedTypologies: [
      'col-rect',
      'col-circ',
      'col-sqr',
      'col-crb',
      'col-frk',
      'col-tpr',
      'col-hol',
      'col-pil',
      'col-arc',
    ],
  },
  {
    id: 'beam',
    nameTr: 'Kiriş',
    nameEn: 'Beam',
    defaultCode: 'KR',
    ifcClass: 'IfcBeam',
    defaultIfcPredefinedType: 'BEAM',
    category: 'superstructure',
    order: 20,
    description: 'Prefabrik kiriş (IfcBeam).',
    allowedTypologies: [
      'beam-rect',
      'beam-i',
      'beam-t',
      'beam-it',
      'beam-l',
      'beam-u',
      'beam-box',
      'beam-gtr',
      'beam-y',
      'beam-ig',
      'beam-spd',
      'beam-cap',
      'beam-prl',
      'beam-crn',
      'beam-lnt',
    ],
  },
  {
    id: 'slab',
    nameTr: 'Döşeme',
    nameEn: 'Slab',
    defaultCode: 'DS',
    ifcClass: 'IfcSlab',
    defaultIfcPredefinedType: 'FLOOR',
    category: 'superstructure',
    order: 30,
    description: 'Prefabrik döşeme (IfcSlab).',
    allowedTypologies: ['slab-hc', 'slab-dt', 'slab-st', 'slab-sol', 'slab-fil', 'slab-rib', 'slab-rf'],
  },
  {
    id: 'wall',
    nameTr: 'Duvar Paneli',
    nameEn: 'Wall Panel',
    defaultCode: 'DP',
    ifcClass: 'IfcWall',
    defaultIfcPredefinedType: 'SOLIDWALL',
    category: 'superstructure',
    order: 40,
    description: 'Prefabrik duvar paneli (IfcWall).',
    allowedTypologies: [
      'wall-sol',
      'wall-swp',
      'wall-fac',
      'wall-gfr',
      'wall-shr',
      'wall-prt',
      'wall-prp',
      'wall-rtn',
      'wall-l',
      'wall-u',
    ],
  },
  {
    id: 'stair',
    nameTr: 'Merdiven',
    nameEn: 'Stair Flight',
    defaultCode: 'MR',
    ifcClass: 'IfcStairFlight',
    defaultIfcPredefinedType: 'STRAIGHT',
    category: 'superstructure',
    order: 50,
    description: 'Prefabrik merdiven kolu (IfcStairFlight).',
    allowedTypologies: ['stair-str', 'stair-l', 'stair-u', 'stair-spr'],
  },
  {
    id: 'landing',
    nameTr: 'Sahanlık',
    nameEn: 'Landing',
    defaultCode: 'SH',
    ifcClass: 'IfcSlab',
    defaultIfcPredefinedType: 'LANDING',
    category: 'superstructure',
    order: 55,
    description: 'Merdiven sahanlığı (IfcSlab/LANDING).',
    allowedTypologies: ['landing-rect', 'landing-l'],
  },
  {
    id: 'corbel',
    nameTr: 'Konsol',
    nameEn: 'Corbel',
    defaultCode: 'KN',
    ifcClass: 'IfcMember',
    defaultIfcPredefinedType: 'BRACE',
    category: 'superstructure',
    order: 60,
    description: 'Bağımsız konsol eleman (IfcMember).',
    allowedTypologies: ['corbel-rect', 'corbel-tpr'],
  },
  {
    id: 'socket',
    nameTr: 'Kolon Temel Soketi',
    nameEn: 'Column Cup / Socket Footing',
    defaultCode: 'SK',
    ifcClass: 'IfcFooting',
    defaultIfcPredefinedType: 'PAD_FOOTING',
    category: 'superstructure',
    order: 65,
    description: 'Prefabrik soket temel (IfcFooting/PAD_FOOTING).',
    allowedTypologies: ['socket-cup'],
  },
  {
    id: 'truss',
    nameTr: 'Çatı Makası',
    nameEn: 'Roof Truss / Girder',
    defaultCode: 'MK',
    ifcClass: 'IfcBeam',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'superstructure',
    order: 70,
    description: 'Prefabrik çatı makası (IfcBeam/USERDEFINED).',
    allowedTypologies: ['truss-flt', 'truss-y', 'truss-gbl'],
  },
]

export const ELEMENT_TYPES_BY_ID: Record<string, ElementTypeCatalogEntry> = Object.fromEntries(
  ELEMENT_TYPES.map((e) => [e.id, e]),
)
