import type { ElementTypeCatalogEntry } from '../types'

/**
 * Üst yapı dışındaki domain elemanları (IFC 4.3 uyumlu isimlendirme — mock katalog).
 * Tipoloji alanları mevcut üst yapı tipolojilerinden yer tutucu olarak eşlenir.
 */
const T = ['beam-rect'] as const

export const ELEMENT_TYPES_EXTENDED: ElementTypeCatalogEntry[] = [
  // Altyapı
  {
    id: 'inf-pile-pre',
    nameTr: 'Fore Kazık (Prefabrik)',
    nameEn: 'Precast driven pile',
    defaultCode: 'FK',
    ifcClass: 'IfcPile',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'substructure',
    order: 10,
    description: 'Prefabrik beton / kompozit kazık (IfcPile, PRECAST_CONCRETE üretim).',
    allowedTypologies: [...T],
  },
  {
    id: 'inf-pile-cap',
    nameTr: 'Kazık Başlığı',
    nameEn: 'Pile cap',
    defaultCode: 'KB',
    ifcClass: 'IfcFooting',
    defaultIfcPredefinedType: 'PILE_CAP',
    category: 'substructure',
    order: 20,
    description: 'Kazık grubu üstü betonarme / prefabrik başlık (IfcFooting/PILE_CAP).',
    allowedTypologies: [...T],
  },
  {
    id: 'inf-strip-foot',
    nameTr: 'Şerit Temel',
    nameEn: 'Strip footing',
    defaultCode: 'ŞT',
    ifcClass: 'IfcFooting',
    defaultIfcPredefinedType: 'STRIP_FOOTING',
    category: 'substructure',
    order: 30,
    description: 'Taşıyıcı duvar altı şerit temel.',
    allowedTypologies: [...T],
  },
  {
    id: 'inf-culvert',
    nameTr: 'Menfez / Kulp',
    nameEn: 'Box culvert',
    defaultCode: 'MF',
    ifcClass: 'IfcPipeSegment',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'substructure',
    order: 40,
    description: 'Kapalı menfez — IFC Pset_PipeSegmentTypeCulvert semantiği (mock).',
    allowedTypologies: [...T],
  },
  {
    id: 'inf-manhole',
    nameTr: 'Menhol Gövdesi',
    nameEn: 'Manhole chamber',
    defaultCode: 'MH',
    ifcClass: 'IfcBuildingElementProxy',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'substructure',
    order: 50,
    description: 'Kanalizasyon / yağmur suyu menhol prefabrik gövde.',
    allowedTypologies: [...T],
  },
  {
    id: 'inf-u-drain',
    nameTr: 'U Oluk / Drenaj Elemanı',
    nameEn: 'U-channel drain',
    defaultCode: 'UO',
    ifcClass: 'IfcPipeSegment',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'substructure',
    order: 60,
    description: 'Yüzey suyu toplama U elemanı.',
    allowedTypologies: [...T],
  },
  // Çevre koruma
  {
    id: 'env-noise-wall',
    nameTr: 'Gürültü Bariyeri Paneli',
    nameEn: 'Noise barrier panel',
    defaultCode: 'GB',
    ifcClass: 'IfcWall',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'environmental_protection',
    order: 10,
    description: 'Otoyol / hat gürültü bariyeri prefabrik panel.',
    allowedTypologies: [...T],
  },
  {
    id: 'env-retain-seg',
    nameTr: 'İstinat Segmenti',
    nameEn: 'Retaining wall segment',
    defaultCode: 'İS',
    ifcClass: 'IfcWall',
    defaultIfcPredefinedType: 'RETAININGWALL',
    category: 'environmental_protection',
    order: 20,
    description: 'L şerit / gravite istinat prefabrik segment.',
    allowedTypologies: [...T],
  },
  {
    id: 'env-safety-plat',
    nameTr: 'Yüksek Güvenlik Bariyeri',
    nameEn: 'Safety barrier segment',
    defaultCode: 'YB',
    ifcClass: 'IfcMember',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'environmental_protection',
    order: 30,
    description: 'Yol güvenliği çelik-beton kompozit bariyer modülü.',
    allowedTypologies: [...T],
  },
  // Çevre düzenleme
  {
    id: 'land-curb',
    nameTr: 'Bordür Taşı',
    nameEn: 'Kerb stone',
    defaultCode: 'BR',
    ifcClass: 'IfcBuildingElementProxy',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'landscaping',
    order: 10,
    description: 'Kaldırım bordürü prefabrik eleman.',
    allowedTypologies: [...T],
  },
  {
    id: 'land-paver',
    nameTr: 'Parke / Taş Slab',
    nameEn: 'Paving slab',
    defaultCode: 'PK',
    ifcClass: 'IfcSlab',
    defaultIfcPredefinedType: 'BASESLAB',
    category: 'landscaping',
    order: 20,
    description: 'Peyzaj döşeme prefabrik ünite.',
    allowedTypologies: [...T],
  },
  {
    id: 'land-tree-grate',
    nameTr: 'Ağaç Izgarası',
    nameEn: 'Tree grille frame',
    defaultCode: 'Aİ',
    ifcClass: 'IfcCovering',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'landscaping',
    order: 30,
    description: 'Kaldırım ağağ çukuru ızgarası modülü.',
    allowedTypologies: [...T],
  },
  // Enerji nakil
  {
    id: 'en-trench',
    nameTr: 'Kablo Kanalı / Tranche',
    nameEn: 'Cable trench unit',
    defaultCode: 'KK',
    ifcClass: 'IfcCableCarrierSegment',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'energy_carrier',
    order: 10,
    description: 'Orta gerilim / haberleşme hat kanalı prefabrik U elemanı.',
    allowedTypologies: [...T],
  },
  {
    id: 'en-vault',
    nameTr: 'Kablo Tavası',
    nameEn: 'Cable tray segment',
    defaultCode: 'KT',
    ifcClass: 'IfcCableCarrierSegment',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'energy_carrier',
    order: 20,
    description: 'Trapez tava / rörüzör modülü.',
    allowedTypologies: [...T],
  },
  {
    id: 'en-hv-plinth',
    nameTr: 'Trafo Plintası',
    nameEn: 'Transformer plinth',
    defaultCode: 'TP',
    ifcClass: 'IfcFooting',
    defaultIfcPredefinedType: 'PAD_FOOTING',
    category: 'energy_carrier',
    order: 30,
    description: 'OG trafo / Hücre temel plintası.',
    allowedTypologies: [...T],
  },
  // Özel imalat
  {
    id: 'cst-facade',
    nameTr: 'Özel Cephe Ünitesi',
    nameEn: 'Custom facade unit',
    defaultCode: 'ÖC',
    ifcClass: 'IfcBuildingElementProxy',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'custom_prefab',
    order: 10,
    description: 'Projeye özel cephe / mimari beton ünite.',
    allowedTypologies: [...T],
  },
  {
    id: 'cst-bridge-deck',
    nameTr: 'Köprü Deck Paneli',
    nameEn: 'Bridge deck panel',
    defaultCode: 'DP',
    ifcClass: 'IfcSlab',
    defaultIfcPredefinedType: 'USERDEFINED',
    category: 'custom_prefab',
    order: 20,
    description: 'Segmental köprü üstyapı paneli.',
    allowedTypologies: [...T],
  },
  {
    id: 'cst-viaduct',
    nameTr: 'Viyadük Segmenti',
    nameEn: 'Viaduct segment',
    defaultCode: 'VS',
    ifcClass: 'IfcBeam',
    defaultIfcPredefinedType: 'GIRDER_SEGMENT',
    category: 'custom_prefab',
    order: 30,
    description: 'Dış hat viyadük prefabrik segment (IfcBeam/GIRDER_SEGMENT).',
    allowedTypologies: [...T],
  },
]
