import type { Typology } from '../types'

/**
 * Tüm üst yapı tipolojileri — master liste dosyalarından (03-07) derlendi.
 * Toplam 46 tipoloji: 9 kolon + 15 kiriş + 7 döşeme + 10 duvar + 4 merdiven +
 * 2 sahanlık + 2 konsol + 1 soket + 3 makas = 46.
 */
export const TYPOLOGIES: Typology[] = [
  // ========== KOLON (9) ==========
  {
    id: 'col-rect',
    elementTypeId: 'col',
    nameTr: 'Dikdörtgen Kolon',
    nameEn: 'Rectangular Column',
    defaultCode: 'RECT',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: ['height', 'sectionWidth', 'sectionDepth'],
    defaultSizeFormatId: 'length_m_section_cm',
    geometryHint: { type: 'extrusion', section: 'rectangle', axis: 'Z' },
    notes: 'En yaygın prefabrik kolon tipi. 40×40 — 80×80 aralığı yaygın.',
  },
  {
    id: 'col-circ',
    elementTypeId: 'col',
    nameTr: 'Dairesel Kolon',
    nameEn: 'Circular Column',
    defaultCode: 'CIRC',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: ['height', 'diameter'],
    defaultSizeFormatId: 'length_m_diameter_cm',
    geometryHint: { type: 'extrusion', section: 'circle', axis: 'Z' },
    notes: 'Mimari ve endüstriyel kullanım.',
  },
  {
    id: 'col-sqr',
    elementTypeId: 'col',
    nameTr: 'Kare Kolon',
    nameEn: 'Square Column',
    defaultCode: 'SQR',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: ['height', 'sectionSize'],
    defaultSizeFormatId: 'length_m',
    geometryHint: { type: 'extrusion', section: 'square', axis: 'Z' },
    notes: 'Dikdörtgen özel durumu; sectionWidth=sectionDepth.',
  },
  {
    id: 'col-crb',
    elementTypeId: 'col',
    nameTr: 'Guseli Kolon',
    nameEn: 'Corbel Column',
    defaultCode: 'CRB',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: [
      'height',
      'sectionWidth',
      'sectionDepth',
      'corbelWidth',
      'corbelHeight',
      'corbelProjection',
      'corbelLevel',
    ],
    defaultSizeFormatId: 'length_m',
    geometryHint: { type: 'extrusion', section: 'rectangle_with_corbel', axis: 'Z' },
    notes: 'Kiriş oturma için konsol çıkıntılı (guse).',
  },
  {
    id: 'col-frk',
    elementTypeId: 'col',
    nameTr: 'Çatallı Kolon',
    nameEn: 'Fork-Head Column',
    defaultCode: 'FRK',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: ['height', 'sectionWidth', 'sectionDepth', 'forkDepth', 'forkOpening'],
    defaultSizeFormatId: 'length_m',
    notes: 'Çift T veya makas oturtmak için üstte çatal ağzı.',
  },
  {
    id: 'col-tpr',
    elementTypeId: 'col',
    nameTr: 'Daralan Kolon',
    nameEn: 'Tapered Column',
    defaultCode: 'TPR',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: ['height', 'baseWidth', 'baseDepth', 'topWidth', 'topDepth'],
    defaultSizeFormatId: 'length_m',
    notes: 'Değişken kesit; mimari kullanım.',
  },
  {
    id: 'col-hol',
    elementTypeId: 'col',
    nameTr: 'Boşluklu Kolon',
    nameEn: 'Hollow Column',
    defaultCode: 'HOL',
    ifcPredefinedType: 'COLUMN',
    identifyingDimensions: ['height', 'outerWidth', 'outerDepth', 'wallThickness'],
    defaultSizeFormatId: 'length_m',
    notes: 'İçi boş; hafifletme veya tesisat.',
  },
  {
    id: 'col-pil',
    elementTypeId: 'col',
    nameTr: 'Pilastır',
    nameEn: 'Pilaster',
    defaultCode: 'PIL',
    ifcPredefinedType: 'PILASTER',
    identifyingDimensions: ['height', 'sectionWidth', 'sectionDepth'],
    defaultSizeFormatId: 'length_m',
    notes: 'Duvar içine gömülü kolon.',
  },
  {
    id: 'col-arc',
    elementTypeId: 'col',
    nameTr: 'Mimari Kolon',
    nameEn: 'Architectural Column',
    defaultCode: 'ARC',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'ArchitecturalColumn',
    identifyingDimensions: ['height', 'sectionWidth', 'sectionDepth', 'profileDescriptor'],
    defaultSizeFormatId: 'length_m',
    notes: 'Dekoratif; yiv / kabartma / kaplama varyasyonu.',
  },

  // ========== KIRIŞ (15) ==========
  {
    id: 'beam-rect',
    elementTypeId: 'beam',
    nameTr: 'Dikdörtgen Kiriş',
    nameEn: 'Rectangular Beam',
    defaultCode: 'RECT',
    ifcPredefinedType: 'BEAM',
    identifyingDimensions: ['span', 'width', 'height'],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'Hatıl, döşeme desteği.',
  },
  {
    id: 'beam-i',
    elementTypeId: 'beam',
    nameTr: 'I Kiriş',
    nameEn: 'I-Beam',
    defaultCode: 'I',
    ifcPredefinedType: 'BEAM',
    identifyingDimensions: [
      'span',
      'totalHeight',
      'flangeWidth',
      'webThickness',
      'flangeThickness',
    ],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'Geniş açıklık çatı / döşeme.',
  },
  {
    id: 'beam-t',
    elementTypeId: 'beam',
    nameTr: 'T Kiriş',
    nameEn: 'T-Beam',
    defaultCode: 'T',
    ifcPredefinedType: 'T_BEAM',
    identifyingDimensions: ['span', 'totalHeight', 'flangeWidth', 'webWidth', 'flangeThickness'],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'Döşeme ile kompozit çalışır. 6m–24m açıklık.',
  },
  {
    id: 'beam-it',
    elementTypeId: 'beam',
    nameTr: 'Ters T Kiriş',
    nameEn: 'Inverted-T Beam',
    defaultCode: 'IT',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'InvertedTBeam',
    identifyingDimensions: [
      'span',
      'totalHeight',
      'bottomFlangeWidth',
      'webWidth',
      'flangeThickness',
    ],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'İki yandan döşeme taşır.',
  },
  {
    id: 'beam-l',
    elementTypeId: 'beam',
    nameTr: 'L Kiriş',
    nameEn: 'L-Beam',
    defaultCode: 'L',
    ifcPredefinedType: 'EDGEBEAM',
    identifyingDimensions: ['span', 'totalHeight', 'flangeWidth', 'webWidth', 'flangeThickness'],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'Tek taraflı kenar döşeme.',
  },
  {
    id: 'beam-u',
    elementTypeId: 'beam',
    nameTr: 'U / Oluk Kiriş',
    nameEn: 'U / Channel Beam',
    defaultCode: 'U',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'UBeam',
    identifyingDimensions: ['span', 'totalHeight', 'outerWidth', 'wallThickness'],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'Oluk profili / kanal.',
  },
  {
    id: 'beam-box',
    elementTypeId: 'beam',
    nameTr: 'Kutu Kiriş',
    nameEn: 'Box Beam',
    defaultCode: 'BOX',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'BoxBeam',
    identifyingDimensions: ['span', 'outerWidth', 'outerHeight', 'wallThickness'],
    defaultSizeFormatId: 'span_cm_section',
    notes: 'Köprü, uzun açıklık.',
  },
  {
    id: 'beam-gtr',
    elementTypeId: 'beam',
    nameTr: 'Oluk Kiriş',
    nameEn: 'Gutter Beam',
    defaultCode: 'GTR',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'GutterBeam',
    identifyingDimensions: ['span', 'outerWidth', 'outerHeight', 'channelDepth', 'channelWidth'],
    defaultSizeFormatId: 'span_cm',
    notes: 'Su drenaj kombo kiriş.',
  },
  {
    id: 'beam-y',
    elementTypeId: 'beam',
    nameTr: 'Y / Meyilli Makas Kiriş',
    nameEn: 'Y / Tapered Roof Girder',
    defaultCode: 'Y',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'YGirder',
    identifyingDimensions: ['span', 'startHeight', 'peakHeight', 'endHeight', 'width'],
    defaultSizeFormatId: 'span_m',
    notes: 'Sanayi çatı makas kirişi.',
  },
  {
    id: 'beam-ig',
    elementTypeId: 'beam',
    nameTr: 'I Çatı Makası',
    nameEn: 'I-Roof Girder',
    defaultCode: 'IG',
    ifcPredefinedType: 'GIRDER_SEGMENT',
    identifyingDimensions: [
      'span',
      'startHeight',
      'endHeight',
      'flangeWidth',
      'webThickness',
      'flangeThickness',
    ],
    defaultSizeFormatId: 'span_m',
    notes: 'Değişken kesit I.',
  },
  {
    id: 'beam-spd',
    elementTypeId: 'beam',
    nameTr: 'Söve / Parapet Kirişi',
    nameEn: 'Spandrel Beam',
    defaultCode: 'SPD',
    ifcPredefinedType: 'SPANDREL',
    identifyingDimensions: ['span', 'height', 'width', 'upstandHeight'],
    defaultSizeFormatId: 'span_cm',
    notes: 'Kenar + parapet kombo.',
  },
  {
    id: 'beam-cap',
    elementTypeId: 'beam',
    nameTr: 'Başlık Kirişi',
    nameEn: 'Cap / Hammerhead',
    defaultCode: 'CAP',
    ifcPredefinedType: 'PIERCAP',
    identifyingDimensions: ['span', 'height', 'width', 'corbelProjection'],
    defaultSizeFormatId: 'span_cm',
    notes: 'Köprü başlığı / kolon üstü.',
  },
  {
    id: 'beam-prl',
    elementTypeId: 'beam',
    nameTr: 'Aşık',
    nameEn: 'Purlin',
    defaultCode: 'PRL',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'Purlin',
    identifyingDimensions: ['span', 'width', 'height'],
    defaultSizeFormatId: 'span_cm',
    notes: 'Çatı aşığı, makas üstü.',
  },
  {
    id: 'beam-crn',
    elementTypeId: 'beam',
    nameTr: 'Vinç Kirişi',
    nameEn: 'Crane Beam',
    defaultCode: 'CRN',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'CraneBeam',
    identifyingDimensions: ['span', 'width', 'height', 'railHeight', 'railWidth'],
    defaultSizeFormatId: 'span_cm',
    notes: 'Endüstriyel vinç yolu.',
  },
  {
    id: 'beam-lnt',
    elementTypeId: 'beam',
    nameTr: 'Lento',
    nameEn: 'Lintel',
    defaultCode: 'LNT',
    ifcPredefinedType: 'LINTEL',
    identifyingDimensions: ['span', 'width', 'height'],
    defaultSizeFormatId: 'span_cm',
    notes: 'Kapı / pencere üstü.',
  },

  // ========== DÖŞEME (7) ==========
  {
    id: 'slab-hc',
    elementTypeId: 'slab',
    nameTr: 'Hollow Core Döşeme',
    nameEn: 'Hollow Core Slab',
    defaultCode: 'HC',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'HollowCore',
    identifyingDimensions: ['length', 'width', 'thickness', 'coreCount', 'coreDiameter'],
    defaultSizeFormatId: 'length_cm_thickness_cm',
    geometryHint: {
      type: 'extrusion',
      section: 'hollowcore_profile',
      axis: 'X',
      standardWidth: 1200,
    },
    notes: 'Standart genişlik 1200mm. Kalınlık 150–400mm.',
  },
  {
    id: 'slab-dt',
    elementTypeId: 'slab',
    nameTr: 'Çift T Döşeme',
    nameEn: 'Double-Tee Slab',
    defaultCode: 'DT',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'DoubleTee',
    identifyingDimensions: ['length', 'width', 'depth', 'flangeThickness', 'stemWidth', 'stemCount'],
    defaultSizeFormatId: 'dt_eu_format',
    notes: 'Büyük açıklık; 2400/3000mm genişlik.',
  },
  {
    id: 'slab-st',
    elementTypeId: 'slab',
    nameTr: 'Tek T Döşeme',
    nameEn: 'Single-Tee Slab',
    defaultCode: 'ST',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'SingleTee',
    identifyingDimensions: ['length', 'width', 'depth', 'flangeThickness', 'stemWidth'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Mimari, nadir.',
  },
  {
    id: 'slab-sol',
    elementTypeId: 'slab',
    nameTr: 'Masif Döşeme',
    nameEn: 'Solid Slab',
    defaultCode: 'SOL',
    ifcPredefinedType: 'FLOOR',
    identifyingDimensions: ['length', 'width', 'thickness'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Tam dolu kesit.',
  },
  {
    id: 'slab-fil',
    elementTypeId: 'slab',
    nameTr: 'Filigran / Yarı Dolu',
    nameEn: 'Filigree / Half Slab',
    defaultCode: 'FIL',
    ifcPredefinedType: 'FLOOR',
    identifyingDimensions: ['length', 'width', 'precastThickness', 'toppingThickness'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Ön dökümlü + saha dökümlü.',
  },
  {
    id: 'slab-rib',
    elementTypeId: 'slab',
    nameTr: 'Nervürlü Döşeme',
    nameEn: 'Ribbed Slab',
    defaultCode: 'RIB',
    ifcPredefinedType: 'FLOOR',
    identifyingDimensions: ['length', 'width', 'thickness', 'ribHeight', 'ribSpacing', 'ribCount'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Tek yönlü nervür.',
  },
  {
    id: 'slab-rf',
    elementTypeId: 'slab',
    nameTr: 'Çatı Döşemesi',
    nameEn: 'Roof Slab',
    defaultCode: 'RF',
    ifcPredefinedType: 'ROOF',
    identifyingDimensions: ['length', 'width', 'thickness', 'slopeAngle'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Eğimli üst örtü.',
  },

  // ========== DUVAR PANELİ (10) ==========
  {
    id: 'wall-sol',
    elementTypeId: 'wall',
    nameTr: 'Masif Duvar Paneli',
    nameEn: 'Solid Wall Panel',
    defaultCode: 'SOL',
    ifcPredefinedType: 'SOLIDWALL',
    identifyingDimensions: ['length', 'height', 'thickness'],
    defaultSizeFormatId: 'length_height_thickness',
  },
  {
    id: 'wall-swp',
    elementTypeId: 'wall',
    nameTr: 'Sandviç Panel',
    nameEn: 'Sandwich Wall Panel',
    defaultCode: 'SWP',
    ifcPredefinedType: 'SOLIDWALL',
    identifyingDimensions: ['length', 'height', 'innerThickness', 'coreThickness', 'outerThickness'],
    defaultSizeFormatId: 'length_height_thickness_total',
    geometryHint: { type: 'layered_extrusion', axis: 'Z', layers: ['inner', 'core', 'outer'] },
    notes: 'İç + yalıtım + dış; yaygın cephe. Toplam kalınlık inner+core+outer.',
  },
  {
    id: 'wall-fac',
    elementTypeId: 'wall',
    nameTr: 'Mimari Cephe Paneli',
    nameEn: 'Architectural Facade',
    defaultCode: 'FAC',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'FacadePanel',
    identifyingDimensions: ['length', 'height', 'thickness', 'surfaceFinish'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Taşıyıcı değil; dekoratif kaplama.',
  },
  {
    id: 'wall-gfr',
    elementTypeId: 'wall',
    nameTr: 'GFRC / GRC Panel',
    nameEn: 'GFRC / GRC Panel',
    defaultCode: 'GFR',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'GFRC',
    identifyingDimensions: ['length', 'height', 'shellThickness', 'ribThickness'],
    defaultSizeFormatId: 'length_height_thickness',
    notes: 'Cam elyaf takviyeli; ince kabuk.',
  },
  {
    id: 'wall-shr',
    elementTypeId: 'wall',
    nameTr: 'Perde Duvar',
    nameEn: 'Shear Wall Panel',
    defaultCode: 'SHR',
    ifcPredefinedType: 'SHEAR',
    identifyingDimensions: ['length', 'height', 'thickness'],
    defaultSizeFormatId: 'length_height_thickness',
  },
  {
    id: 'wall-prt',
    elementTypeId: 'wall',
    nameTr: 'Bölme Duvar',
    nameEn: 'Partition Wall',
    defaultCode: 'PRT',
    ifcPredefinedType: 'PARTITIONING',
    identifyingDimensions: ['length', 'height', 'thickness'],
    defaultSizeFormatId: 'length_height_thickness',
  },
  {
    id: 'wall-prp',
    elementTypeId: 'wall',
    nameTr: 'Parapet',
    nameEn: 'Parapet Panel',
    defaultCode: 'PRP',
    ifcPredefinedType: 'PARAPET',
    identifyingDimensions: ['length', 'height', 'thickness'],
    defaultSizeFormatId: 'length_height_thickness',
  },
  {
    id: 'wall-rtn',
    elementTypeId: 'wall',
    nameTr: 'İstinat Paneli',
    nameEn: 'Retaining Wall Panel',
    defaultCode: 'RTN',
    ifcPredefinedType: 'RETAININGWALL',
    identifyingDimensions: ['length', 'height', 'thickness', 'heelWidth', 'keyDepth'],
    defaultSizeFormatId: 'length_height_thickness',
  },
  {
    id: 'wall-l',
    elementTypeId: 'wall',
    nameTr: 'L Profil Duvar',
    nameEn: 'L-Profile Wall',
    defaultCode: 'L',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'LProfileWall',
    identifyingDimensions: ['extrusionHeight', 'legA', 'legB', 'thickness'],
    defaultSizeFormatId: 'extrusion_legs',
    notes: 'Köşe duvar; iki bacaklı extrusion.',
  },
  {
    id: 'wall-u',
    elementTypeId: 'wall',
    nameTr: 'U Profil Duvar',
    nameEn: 'U-Profile Wall',
    defaultCode: 'U',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'UProfileWall',
    identifyingDimensions: ['extrusionHeight', 'legA', 'legB', 'legC', 'thickness'],
    defaultSizeFormatId: 'extrusion_legs',
  },

  // ========== MERDİVEN (4) ==========
  {
    id: 'stair-str',
    elementTypeId: 'stair',
    nameTr: 'Düz Kollu Merdiven',
    nameEn: 'Straight Flight',
    defaultCode: 'STR',
    ifcPredefinedType: 'STRAIGHT',
    identifyingDimensions: ['totalRun', 'totalRise', 'width', 'stepCount', 'treadDepth', 'riserHeight'],
    defaultSizeFormatId: 'run_rise_width',
  },
  {
    id: 'stair-l',
    elementTypeId: 'stair',
    nameTr: 'L Merdiven',
    nameEn: 'L-Shaped Stair',
    defaultCode: 'L',
    ifcPredefinedType: 'WINDER',
    identifyingDimensions: ['runA', 'runB', 'totalRise', 'width', 'stepCount', 'landingPosition'],
    defaultSizeFormatId: 'l_stair_format',
  },
  {
    id: 'stair-u',
    elementTypeId: 'stair',
    nameTr: 'U / Geri Dönüşlü Merdiven',
    nameEn: 'Half-Turn / Switchback',
    defaultCode: 'U',
    ifcPredefinedType: 'HALF_TURN_STAIR',
    identifyingDimensions: ['runA', 'runB', 'totalRise', 'width', 'stepCount', 'gapWidth'],
    defaultSizeFormatId: 'l_stair_format',
  },
  {
    id: 'stair-spr',
    elementTypeId: 'stair',
    nameTr: 'Helezon Merdiven',
    nameEn: 'Spiral Stair',
    defaultCode: 'SPR',
    ifcPredefinedType: 'SPIRAL_STAIR',
    identifyingDimensions: ['outerDiameter', 'innerDiameter', 'totalRise', 'stepCount', 'totalAngle'],
    defaultSizeFormatId: 'spiral_dia_rise',
  },

  // ========== SAHANLIK (2) ==========
  {
    id: 'landing-rect',
    elementTypeId: 'landing',
    nameTr: 'Dikdörtgen Sahanlık',
    nameEn: 'Rectangular Landing',
    defaultCode: 'RECT',
    ifcPredefinedType: 'LANDING',
    identifyingDimensions: ['length', 'width', 'thickness'],
    defaultSizeFormatId: 'length_height_thickness',
  },
  {
    id: 'landing-l',
    elementTypeId: 'landing',
    nameTr: 'L Sahanlık',
    nameEn: 'L-Landing',
    defaultCode: 'L',
    ifcPredefinedType: 'LANDING',
    identifyingDimensions: ['legA', 'legB', 'width', 'thickness'],
    defaultSizeFormatId: 'extrusion_legs',
  },

  // ========== KONSOL (2) ==========
  {
    id: 'corbel-rect',
    elementTypeId: 'corbel',
    nameTr: 'Dikdörtgen Konsol',
    nameEn: 'Rectangular Corbel',
    defaultCode: 'RECT',
    ifcPredefinedType: 'BRACE',
    identifyingDimensions: ['projection', 'width', 'height'],
    defaultSizeFormatId: 'projection_wxh',
  },
  {
    id: 'corbel-tpr',
    elementTypeId: 'corbel',
    nameTr: 'Eğimli Konsol',
    nameEn: 'Tapered Corbel',
    defaultCode: 'TPR',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'TaperedCorbel',
    identifyingDimensions: ['projection', 'width', 'rootHeight', 'tipHeight'],
    defaultSizeFormatId: 'projection_wxh',
  },

  // ========== SOKET (1) ==========
  {
    id: 'socket-cup',
    elementTypeId: 'socket',
    nameTr: 'Soket Temel',
    nameEn: 'Cup / Socket Footing',
    defaultCode: 'CUP',
    ifcPredefinedType: 'PAD_FOOTING',
    identifyingDimensions: [
      'outerLength',
      'outerWidth',
      'totalHeight',
      'socketLength',
      'socketWidth',
      'socketDepth',
    ],
    defaultSizeFormatId: 'socket_full',
  },

  // ========== ÇATI MAKASI (3) ==========
  {
    id: 'truss-flt',
    elementTypeId: 'truss',
    nameTr: 'Düz Makas',
    nameEn: 'Flat Truss',
    defaultCode: 'FLT',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'FlatTruss',
    identifyingDimensions: ['span', 'height', 'width'],
    defaultSizeFormatId: 'span_m',
  },
  {
    id: 'truss-y',
    elementTypeId: 'truss',
    nameTr: 'Y Makas',
    nameEn: 'Y-Truss',
    defaultCode: 'Y',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'YTruss',
    identifyingDimensions: ['span', 'startHeight', 'peakHeight', 'endHeight', 'width'],
    defaultSizeFormatId: 'span_m',
  },
  {
    id: 'truss-gbl',
    elementTypeId: 'truss',
    nameTr: 'Beşik Makas',
    nameEn: 'Gable Truss',
    defaultCode: 'GBL',
    ifcPredefinedType: 'USERDEFINED',
    ifcObjectType: 'GableTruss',
    identifyingDimensions: ['span', 'eaveHeight', 'peakHeight', 'width', 'slopeAngle'],
    defaultSizeFormatId: 'span_m',
  },
]

export const TYPOLOGIES_BY_ID: Record<string, Typology> = Object.fromEntries(
  TYPOLOGIES.map((t) => [t.id, t]),
)

export function getTypologiesForElementType(elementTypeId: string): Typology[] {
  return TYPOLOGIES.filter((t) => t.elementTypeId === elementTypeId)
}
