import type { WidgetCatalogEntry, WidgetType } from './types'

export const WIDGET_CATALOG: WidgetCatalogEntry[] = [
  {
    type: 'kpi',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    defaultSettings: { kpiKey: 'projects' },
  },
  {
    type: 'notifications',
    categoryKey: 'dashboard.catalog.category.actions',
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 3,
    defaultSettings: { notificationFilter: 'all', limit: 8 },
  },
  {
    type: 'actions',
    categoryKey: 'dashboard.catalog.category.actions',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
    defaultSettings: { limit: 6 },
  },
  {
    type: 'list',
    categoryKey: 'dashboard.catalog.category.lists',
    defaultW: 6,
    defaultH: 5,
    minW: 4,
    minH: 3,
    defaultSettings: { listSource: 'projects', limit: 8 },
  },
  {
    type: 'chart',
    categoryKey: 'dashboard.catalog.category.charts',
    defaultW: 6,
    defaultH: 5,
    minW: 4,
    minH: 3,
    defaultSettings: { chartType: 'line', dataSource: 'monthlyProduction' },
  },
  {
    type: 'gauge',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 3,
    defaultH: 3,
    minW: 2,
    minH: 2,
    defaultSettings: { gaugeValue: 72, gaugeMax: 100 },
  },
  {
    type: 'heatmap',
    categoryKey: 'dashboard.catalog.category.charts',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  {
    type: 'funnel',
    categoryKey: 'dashboard.catalog.category.charts',
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 3,
    defaultSettings: { dataSource: 'quoteStages' },
  },
  {
    type: 'topn',
    categoryKey: 'dashboard.catalog.category.lists',
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    defaultSettings: { limit: 5 },
  },
  {
    type: 'calendar',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 3,
  },
  {
    type: 'activity',
    categoryKey: 'dashboard.catalog.category.actions',
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 3,
    defaultSettings: { limit: 10 },
  },
  {
    type: 'quickActions',
    categoryKey: 'dashboard.catalog.category.actions',
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
  {
    type: 'text',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 6,
    defaultH: 2,
    minW: 2,
    minH: 2,
    defaultSettings: {
      textContent: '',
      textAlign: 'left',
      textSize: 'lg',
      textColor: 'default',
      textWeight: 'semibold',
      showHeader: false,
    },
  },
  {
    type: 'markdown',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 4,
    defaultH: 3,
    minW: 2,
    minH: 2,
    defaultSettings: { note: '', showHeader: false },
    comingSoon: true,
  },
  {
    type: 'clock',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
  },
  {
    type: 'map',
    categoryKey: 'dashboard.catalog.category.other',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  {
    type: 'moldStatus',
    categoryKey: 'dashboard.catalog.category.production',
    defaultW: 12,
    defaultH: 8,
    minW: 6,
    minH: 5,
    defaultSettings: { showEmptyMolds: true, moldBandFilter: 'all' },
  },
  {
    type: 'iframe',
    categoryKey: 'dashboard.catalog.category.other',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
    comingSoon: true,
  },
  {
    type: 'currency',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    defaultSettings: { currencySymbols: 'USD,EUR,GBP' },
  },
  {
    type: 'weather',
    categoryKey: 'dashboard.catalog.category.general',
    defaultW: 5,
    defaultH: 5,
    minW: 4,
    minH: 4,
    defaultSettings: {
      weatherLocationMode: 'preset',
      weatherRegion: 'marmara',
      weatherCity: 'istanbul',
    },
  },
]

export function catalogEntryFor(type: WidgetType): WidgetCatalogEntry {
  return WIDGET_CATALOG.find((e) => e.type === type) ?? WIDGET_CATALOG[0]!
}
