import type {
  CostRow,
  JobContext,
  MaterialAssembly,
  MaterialItem,
  PieceMarkTemplate,
  ProductionInstanceRow,
  ProductionPiece,
  StandardMaterialRow,
  TemplateAssemblyRow,
  TemplateMaterialRow,
} from './types'

export const initialMaterialItems: MaterialItem[] = [
  {
    id: 'mi-1',
    category: 'Rebar',
    materialNum: 'M-440C',
    embedLabel: 'EMB-01',
    description: '#4 Epoxy',
    bendType: 'Std',
    materialCost: 1.25,
    matWeight: 0.12,
    glCode: '5.2001',
    bomUnit: 'LB',
    purchaseUnit: 'LB',
    unitConversion: 1,
    materialWaste: 3,
    orderBy: 10,
    dimLength: 20,
    fileName: null,
    customFields: Array.from({ length: 10 }, (_, i) => (i === 0 ? 'Plant-A' : '')),
    advanceOrder: false,
    active: true,
    production: true,
    cip: true,
    erection: true,
  },
  {
    id: 'mi-2',
    category: 'Insert',
    materialNum: 'INS-882',
    embedLabel: 'EMB-02',
    description: 'Lifting insert 2.5T',
    bendType: '—',
    materialCost: 42,
    matWeight: 1.1,
    glCode: '5.2100',
    bomUnit: 'EA',
    purchaseUnit: 'EA',
    unitConversion: 1,
    materialWaste: 0,
    orderBy: 20,
    dimLength: 0,
    fileName: 'insert-spec.pdf',
    customFields: Array.from({ length: 10 }, () => ''),
    advanceOrder: true,
    active: true,
    production: true,
    cip: false,
    erection: true,
  },
  {
    id: 'mi-3',
    category: 'Strand',
    materialNum: 'ST-12',
    embedLabel: '—',
    description: '½" strand',
    bendType: '—',
    materialCost: 0.85,
    matWeight: 0.05,
    glCode: '5.3000',
    bomUnit: 'LF',
    purchaseUnit: 'LF',
    unitConversion: 1,
    materialWaste: 2,
    orderBy: 5,
    dimLength: 100,
    fileName: null,
    customFields: Array.from({ length: 10 }, () => ''),
    advanceOrder: false,
    active: true,
    production: true,
    cip: true,
    erection: false,
  },
]

const al = (
  id: string,
  cat: MaterialItem['category'],
  itemId: string,
  num: string,
  ob: number,
  q: number,
  dl: number,
  bt: string,
  a: number,
  b: number,
  c: number,
  d: number,
  e: number,
  f: number,
) => ({
  id,
  category: cat,
  itemId,
  materialNum: num,
  orderBy: ob,
  qty: q,
  dimLength: dl,
  bendType: bt,
  dimA: a,
  dimB: b,
  dimC: c,
  dimD: d,
  dimE: e,
  dimF: f,
})

export const initialMaterialAssemblies: MaterialAssembly[] = [
  {
    id: 'ma-1',
    category: 'Assembly Kit',
    materialNum: 'ASM-2044',
    embedLabel: 'ASM-EMB',
    description: 'Rebar cage + inserts',
    bendType: 'Std',
    glCode: '5.5001',
    bomUnit: 'EA',
    purchaseUnit: 'EA',
    unitConversion: 1,
    materialWaste: 1,
    orderBy: 1,
    materialCost: 850,
    matWeight: 420,
    fileName: null,
    advanceOrder: false,
    active: true,
    production: true,
    cip: true,
    erection: true,
    lines: [
      al('l1', 'Rebar', 'mi-1', 'M-440C', 10, 120, 20, 'Std', 12, 8, 6, 4, 3, 2),
      al('l2', 'Insert', 'mi-2', 'INS-882', 20, 4, 0, '—', 0, 0, 0, 0, 0, 0),
    ],
  },
  {
    id: 'ma-2',
    category: 'Assembly Kit',
    materialNum: 'ASM-3100',
    embedLabel: '—',
    description: 'Strand bundle',
    bendType: '—',
    glCode: '5.5002',
    bomUnit: 'EA',
    purchaseUnit: 'EA',
    unitConversion: 1,
    materialWaste: 0,
    orderBy: 2,
    materialCost: 210,
    matWeight: 88,
    fileName: null,
    advanceOrder: false,
    active: true,
    production: true,
    cip: false,
    erection: false,
    lines: [al('l3', 'Strand', 'mi-3', 'ST-12', 1, 200, 100, '—', 0, 0, 0, 0, 0, 0)],
  },
]

function tmplRow(
  id: string,
  cat: TemplateMaterialRow['category'],
  num: string,
  emb: string,
  desc: string,
  qty: number,
  cost: number,
  w: number,
  u: string,
  bt: string,
  dl: number,
): TemplateMaterialRow {
  return {
    id,
    category: cat,
    materialNum: num,
    embedLabel: emb,
    description: desc,
    qty,
    cost,
    weight: w,
    unit: u,
    bendType: bt,
    dimLength: dl,
  }
}

function asmRow(
  id: string,
  cat: TemplateAssemblyRow['category'],
  num: string,
  emb: string,
  desc: string,
  qty: number,
  cost: number,
  w: number,
  u: string,
  bt: string,
  dl: number,
): TemplateAssemblyRow {
  return {
    id,
    category: cat,
    materialNum: num,
    embedLabel: emb,
    description: desc,
    qty,
    cost,
    weight: w,
    unit: u,
    bendType: bt,
    dimLength: dl,
  }
}

function costRow(
  id: string,
  ct: string,
  sec: string,
  qty: number,
  unit: string,
  cost: number,
  calc: CostRow['calcType'],
  oh: number,
  pr: number,
  margin: number,
  ut: boolean,
  st: boolean,
): CostRow {
  return {
    id,
    costType: ct,
    section: sec,
    qty,
    unit,
    cost,
    calcType: calc,
    overhead: oh,
    profit: pr,
    margin,
    useTax: ut,
    salesTax: st,
  }
}

const defaultHeader = (): PieceMarkTemplate['header'] => ({
  description: 'Double-T flange 12ft',
  pieceMark: 'PM-TPL-2044',
  active: true,
  fileName: null,
  location: 'IST-HAD',
  productCategory: 'Double-T',
  productCode: 'DT-12',
  crossSection: 'DT48',
  note: 'Template baseline',
  rev: 'A',
  revText: 'Initial',
  revDate: '2026-01-15',
  returnLegs: 2,
  lengthFt: 12,
  lengthIn: 0,
  lengthFrac: '0/0',
  widthFt: 4,
  widthIn: 0,
  widthFrac: '0/0',
  depthFt: 2,
  depthIn: 6,
  depthFrac: '0/0',
  weight: 18500,
  structCy: 12.4,
  archCy: 0.8,
  releaseStr: '4500',
  structSf: 220,
  archSf: 18,
  day28Release: '5000',
  braceType: 'Pipe',
  braceQty: 4,
  addWork: [false, false, true, false, false, false],
})

export const initialTemplates: PieceMarkTemplate[] = [
  {
    id: 'tpl-1',
    location: 'IST-HAD',
    pieceMark: 'PM-TPL-2044',
    description: 'Double-T flange 12ft',
    productCategory: 'Double-T',
    productCode: 'DT-12',
    crossSection: 'DT48',
    active: true,
    header: defaultHeader(),
    materialItems: [
      tmplRow('tm1', 'Rebar', 'M-440C', 'EMB-01', '#4 Epoxy', 120, 1.25, 0.12, 'LB', 'Std', 20),
      tmplRow('tm2', 'Insert', 'INS-882', 'EMB-02', 'Lifting insert 2.5T', 4, 42, 1.1, 'EA', '—', 0),
    ],
    materialAssemblies: [
      asmRow('ta1', 'Assembly Kit', 'ASM-2044', 'ASM-EMB', 'Rebar cage + inserts', 1, 850, 420, 'EA', 'Std', 0),
    ],
    costs: [
      costRow('c1', 'Concrete CY', 'Structure', 13.2, 'CY', 1200, 'Rollup', 240, 180, 12, true, true),
      costRow('c2', 'Material Items', 'Materials', 1, 'LS', 850, 'Rollup', 0, 0, 0, false, false),
      costRow('c3', 'Material Assemblies', 'Materials', 1, 'LS', 850, 'Rollup', 0, 0, 0, false, false),
      costRow('c4', 'Labor', 'Labor', 42, 'H', 65, 'Manual', 10, 0, 8, false, false),
      costRow('c5', 'Overhead', 'OH', 1, 'LS', 400, 'Formula', 0, 0, 0, false, false),
      costRow('c6', 'SGA', 'SG&A', 1, 'LS', 200, 'Manual', 0, 0, 0, false, false),
      costRow('c7', 'Margin', 'Fin', 1, 'LS', 350, 'Manual', 0, 350, 0, false, false),
    ],
  },
  {
    id: 'tpl-2',
    location: 'ANK-02',
    pieceMark: 'PM-TPL-3100',
    description: 'Wall panel W8',
    productCategory: 'Wall',
    productCode: 'WP-8',
    crossSection: 'W8x24',
    active: true,
    header: {
      ...defaultHeader(),
      description: 'Wall panel W8',
      pieceMark: 'PM-TPL-3100',
      location: 'ANK-02',
      productCategory: 'Wall',
      productCode: 'WP-8',
      crossSection: 'W8x24',
    },
    materialItems: [tmplRow('tm3', 'Strand', 'ST-12', '—', '½" strand', 200, 0.85, 0.05, 'LF', '—', 100)],
    materialAssemblies: [],
    costs: [
      costRow('c8', 'Concrete CY', 'Structure', 8, 'CY', 1200, 'Rollup', 100, 80, 10, true, false),
      costRow('c9', 'Labor', 'Labor', 24, 'H', 65, 'Manual', 10, 0, 8, false, false),
    ],
  },
]

function instRow(
  id: string,
  status: string,
  sn: string,
): ProductionInstanceRow {
  return {
    id,
    status,
    ctrlNum: `CTRL-${id}`,
    pieceSn: sn,
    guid: `00000000-0000-4000-8000-${id.padStart(12, '0')}`,
    yardLoc: 'A1-B',
    castDate: '2026-03-01',
    bedName: 'B-12',
    pos: '1',
    loadDate: '2026-03-05',
    loadNo: 'LD-9001',
    qcCheck: 'OK',
    prePour: 'OK',
    postPour: 'OK',
    shipping: 'Ready',
    countCy: 13.2,
    countSf: 238,
    aw: [true, false, true, false, false, false],
  }
}

function stdMatFromTemplate(tplId: string): StandardMaterialRow[] {
  const t = initialTemplates.find((x) => x.id === tplId)
  if (!t) return []
    return t.materialItems.map((m) => ({
    id: `sm-${m.id}`,
    category: m.category,
    materialNum: m.materialNum,
    embedLabel: m.embedLabel,
    description: m.description,
    qty: m.qty,
    prevQty: m.qty,
    actualQty: m.qty,
    prevActualQty: m.qty,
    weight: m.weight,
    unit: m.unit,
    bendType: m.bendType,
    dimLength: m.dimLength,
    fromTemplate: true,
  }))
}

export const initialJobs: JobContext[] = [
  {
    id: 'JOB-4421',
    phases: ['Phase 1', 'Phase 2'],
    plants: ['IST-HAD', 'ANK-02'],
    products: ['Double-T', 'Wall'],
  },
  {
    id: 'JOB-5500',
    phases: ['Phase 1'],
    plants: ['IST-HAD'],
    products: ['Double-T'],
  },
]

export const initialProductionPieces: ProductionPiece[] = [
  {
    id: 'pp-1',
    jobId: 'JOB-4421',
    templateId: 'tpl-1',
    phase: 'Phase 1',
    plant: 'IST-HAD',
    productCategory: 'Double-T',
    productCode: 'DT-12',
    crossSection: 'DT48',
    pieceMark: 'PM-2044A',
    qty: 4,
    drawingStatus: 'Released',
    header: {
      jobId: 'JOB-4421',
      location: 'IST-HAD',
      phase: 'Phase 1',
      productCategory: 'Double-T',
      productType: 'Flange',
      crossSection: 'DT48',
      pieceMark: 'PM-2044A',
      qty: 4,
      drawingStatus: 'Released',
      dateIssued: '2026-02-01',
      lengthFt: 12,
      lengthIn: 0,
      lengthFrac: '0/0',
      widthFt: 4,
      widthIn: 0,
      widthFrac: '0/0',
      depthFt: 2,
      depthIn: 6,
      depthFrac: '0/0',
      weight: 18500,
      note: 'From template PM-TPL-2044',
      rev: 'B',
      revText: 'Field note',
      revDate: '2026-02-10',
      returnLegs: 2,
      structCy: 12.4,
      archCy: 0.8,
      totalCy: 13.2,
      releaseStr: '4500',
      day28Release: '5000',
      structSf: 220,
      archSf: 18,
      totalSf: 238,
      braceType: 'Pipe',
      braceQty: 4,
      drawnBy: 'A.Yılmaz',
      dateDrawn: '2026-01-28',
      checkedBy: 'M.Kaya',
      dateChecked: '2026-01-30',
      addWork: [false, false, true, false, false, false],
    },
    instances: [instRow('i1', 'Cast', 'SN-0001'), instRow('i2', 'Queued', 'SN-0002')],
    standardMaterial: stdMatFromTemplate('tpl-1'),
    jobSpecificMaterial: [
      {
        id: 'js-1',
        category: 'Miscellaneous Items',
        materialNum: 'MISC-01',
        description: 'Field-added shim pack',
        qty: 2,
        actualQty: 2,
        weight: 1,
        unit: 'EA',
      },
    ],
  },
]
