import type { CostRow, PieceMarkTemplate, TemplateAssemblyRow, TemplateMaterialRow } from './types'

export function createEmptyTemplate(id: string): PieceMarkTemplate {
  return {
    id,
    location: 'IST-HAD',
    pieceMark: '',
    description: '',
    productCategory: 'Double-T',
    productCode: '',
    crossSection: '',
    active: true,
    header: {
      description: '',
      pieceMark: '',
      active: true,
      fileName: null,
      location: 'IST-HAD',
      productCategory: 'Double-T',
      productCode: '',
      crossSection: '',
      note: '',
      rev: 'A',
      revText: '',
      revDate: '',
      returnLegs: 0,
      lengthFt: 0,
      lengthIn: 0,
      lengthFrac: '0/0',
      widthFt: 0,
      widthIn: 0,
      widthFrac: '0/0',
      depthFt: 0,
      depthIn: 0,
      depthFrac: '0/0',
      weight: 0,
      structCy: 0,
      archCy: 0,
      releaseStr: '',
      structSf: 0,
      archSf: 0,
      day28Release: '',
      braceType: '',
      braceQty: 0,
      addWork: [false, false, false, false, false, false],
    },
    materialItems: [] as TemplateMaterialRow[],
    materialAssemblies: [] as TemplateAssemblyRow[],
    costs: [] as CostRow[],
  }
}
